#!/usr/bin/env python3
"""Generate the Quarto cookbook index from README tables."""

from __future__ import annotations

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
OUTPUT = ROOT / "cookbooks.qmd"
GENERATED_MARKER = "Generated by scripts/generate_quarto_index.py. Do not edit."

LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
RENDERABLE_EXTENSIONS = {".ipynb", ".md", ".qmd"}
HR_RE = re.compile(r"(?m)^---\s*$")


def generated_markdown_path(source: Path) -> str:
    """Return the generated Quarto path for a Markdown source file."""
    return source.with_suffix(".qmd").relative_to(ROOT).as_posix()


def preview_href(href: str) -> tuple[str, str]:
    """Return the href Quarto can render and a display status."""
    target = ROOT / href

    if target.is_dir():
        readme = target / "README.md"
        if readme.exists():
            return generated_markdown_path(readme), "yes"
        return href, "not rendered"

    if not target.exists():
        return href, "missing"

    if target.suffix == ".md":
        return generated_markdown_path(target), "yes"

    if target.suffix in {".ipynb", ".qmd"}:
        return href, "yes"

    return href, "not rendered"


def rewrite_markdown_links(source: str) -> str:
    """Point local Markdown and HTML links at generated qmd preview files."""

    def replace_markdown_link(match: re.Match[str]) -> str:
        href, suffix = match.groups()
        if re.match(r"^[a-z][a-z0-9+.-]*:", href) or href.startswith("#"):
            return match.group(0)
        return f"]({href[:-3]}.qmd{suffix or ''}"

    def replace_html_link(match: re.Match[str]) -> str:
        href = match.group(1)
        if re.match(r"^[a-z][a-z0-9+.-]*:", href) or href.startswith("#"):
            return match.group(0)
        return f'href="{href[:-3]}.qmd"'

    source = re.sub(r"]\(([^)#?]+\.md)(#[^)]*)?", replace_markdown_link, source)
    return re.sub(r'href="([^"#?]+\.md)"', replace_html_link, source)


def sanitize_markdown(source: str) -> str:
    """Make plain Markdown safer for Quarto's qmd reader."""
    sanitized = HR_RE.sub("***", source)
    sanitized = rewrite_markdown_links(sanitized)
    sanitized = sanitized.replace("./connectors-management.qmd", "./01-connectors-management.qmd")
    return sanitized


def generated_frontmatter(source: Path) -> str:
    """Return frontmatter that marks a generated preview file."""
    return f"---\ntitle: \"{source.stem}\"\nsource-file: \"{source.relative_to(ROOT).as_posix()}\"\ncomments: false\n---\n\n<!-- {GENERATED_MARKER} -->\n\n"


def generate_markdown_previews() -> None:
    """Create sibling qmd files for Markdown sources with safe separators."""
    patterns = (
        "mistral/**/*.md",
        "concept-deep-dive/**/*.md",
        "third_party/**/*.md",
    )
    for pattern in patterns:
        for source in ROOT.glob(pattern):
            target = source.with_suffix(".qmd")
            body = sanitize_markdown(source.read_text(encoding="utf-8"))
            target.write_text(generated_frontmatter(source) + body, encoding="utf-8")


def parse_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    section = ""

    for raw_line in README.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()

        if line == "## Main Notebooks":
            section = "Main notebooks"
            continue
        if line == "## Third Party Tools":
            section = "Third-party tools"
            continue
        if not section or not line.startswith("|"):
            continue
        if re.match(r"^\|\s*:?-+", line) or "Notebook" in line or "Tools" in line:
            continue

        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) < 3:
            continue

        match = LINK_RE.search(cells[0])
        if not match:
            continue

        title, href = match.groups()
        href = href.strip()
        if href.startswith("http"):
            continue

        preview, status = preview_href(href)
        rows.append(
            {
                "section": section,
                "title": title.strip().replace("`", ""),
                "href": href,
                "preview": preview,
                "category": cells[1].strip(),
                "description": cells[2].strip(),
                "status": status,
            }
        )

    return rows


def render(rows: list[dict[str, str]]) -> str:
    lines = [
        "---",
        'title: "Cookbooks"',
        "---",
        "",
        "This page is generated from the cookbook tables in `README.md`.",
        "",
        "```{=html}",
        "<style>",
        ".missing-cookbook { color: #a94442; font-weight: 600; }",
        ".cookbook-path { font-size: 0.9em; color: #666; }",
        "</style>",
        "```",
        "",
    ]

    for section in ("Main notebooks", "Third-party tools"):
        section_rows = [row for row in rows if row["section"] == section]
        lines.extend([f"## {section}", ""])
        for row in section_rows:
            if row["status"] == "missing":
                lines.append(f"### {row['title']} <span class=\"missing-cookbook\">missing locally</span>")
            elif row["status"] == "not rendered":
                lines.append(f"### {row['title']} <span class=\"missing-cookbook\">not rendered by preview</span>")
            else:
                lines.append(f"### [{row['title']}]({row['preview']})")
            lines.append("")
            if row["category"]:
                lines.append(f"**Category:** {row['category']}")
                lines.append("")
            if row["description"]:
                lines.append(row["description"])
                lines.append("")
            lines.append(f"<div class=\"cookbook-path\">{row['href']}</div>")
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    generate_markdown_previews()
    OUTPUT.write_text(render(parse_rows()), encoding="utf-8")


if __name__ == "__main__":
    main()
